name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: pnpm
      - name: Install
        run: pnpm install
      - uses: actions/cache@v4
        with:
            path: |
              ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Build
        run: pnpm run build
      - name: Analyze bundle sizes
        uses: transferwise/actions-next-bundle-analyzer@v2
        with:
          working-directory: ./
          comment-strategy: 'skip-insignificant'
          create-issue: false
          # Optional, defaults to `github.token`.
          github-token: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
